name: Pytest check

on:
  # Trigger the workflow on push or pull request, 
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pytest
        pip install requests

    - name: Running pytest
      run: |
        pytest test_tracks.py
        